name: deploy-My-website-environment
concurrency: My-company

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: MyWebsiteTest
  ENVIRONMENT_TYPE: Test

jobs:
  lint:
    uses: ccie9773/my-website-environment/.github/workflows/lint.yml@main

  # Deploy to the test environment.
  deploy-test:
    uses: ccie9773/my-website-environment/.github/workflows/deploy.yml@main
    needs: lint
    with:
      environmentType: Test
      resourceGroupName: MyWebsiteTest
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}

  # Deploy to the production environment.
  deploy-production:
    uses: ccie/My-website-environment/.github/workflows/deploy.yml@main
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: MyWebsiteProduction
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
